apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-account
  labels:
    app: user-account
    version: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-account
        version: production
    spec:
      containers:
        - name: user-account
          image: 582230774551.dkr.ecr.eu-west-1.amazonaws.com/user-account:10
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
---

apiVersion: v1
kind: Service
metadata:
  name: user-account
  labels:
    app: user-account
spec:
  ports:
    - port: 80
      name: http-user-accounts
      targetPort: 8091
  selector:
    app: user-account
---