apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-profile
  labels:
    app: user-profile
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-profile
        version: v1
    spec:
      containers:
        - name: user-profile
          image: 582230774551.dkr.ecr.eu-west-1.amazonaws.com/user-profile:15
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
---

apiVersion: v1
kind: Service
metadata:
  name: user-profile
  labels:
    app: user-profile
spec:
  ports:
    - port: 80
      name: http-user-profile
      targetPort: 8090
  selector:
    app: user-profile
---