apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: config-service
        version: v1
    spec:
      containers:
        - name: config-service
          image: 582230774551.dkr.ecr.eu-west-1.amazonaws.com/config-service:latest
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8094
---

apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  ports:
    - port: 8094
      name: http-config-service
      targetPort: 8094
      protocol: TCP
  selector:
    app: config-service
---