apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payments-app
  labels:
    app: payments-app
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payments-app
        version: v1
    spec:
      containers:
        - name: payments-app
          image: 582230774551.dkr.ecr.eu-west-1.amazonaws.com/gft-payments-app:latest
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: payments-app
  labels:
    app: payments-app
spec:
  ports:
    - port: 80
      name: http-payments-app
  selector:
    app: payments-app
---
