apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: market-data
  labels:
    app: market-data
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: market-data
        version: v1
    spec:
      containers:
        - name: market-data
          image: 582230774551.dkr.ecr.eu-west-1.amazonaws.com/market-data
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8093
---

apiVersion: v1
kind: Service
metadata:
  name: market-data
  labels:
    app: market-data
spec:
  ports:
    - port: 8093
      name: http-market-data
  selector:
    app: market-data
---