apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: transfer-service
  labels:
    app: transfer-service
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: transfer-service
        version: v1
    spec:
      containers:
        - name: transfer-service
          image: 582230774551.dkr.ecr.eu-west-1.amazonaws.com/transfer-service
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8092
---

apiVersion: v1
kind: Service
metadata:
  name: transfer-service
  labels:
    app: transfer-service
spec:
  ports:
    - port: 8092
      name: http-transfer-service
  selector:
    app: transfer-service
---