---

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mysql-connector
spec:
  hosts:
    - "*"
  ports:
    - number: 3306
      name: tcp
      protocol: tcp
  resolution: DNS
  location: MESH_EXTERNAL

---